name: 'plausible_analytics'

# The runtime the application uses.
type: "elixir:1.14"

# Installs global dependencies as part of the build process. They’re independent of your app’s dependencies and
# are available in the PATH during the build process and in the runtime environment. They’re installed before
# the build hook runs using a package manager for the language.
dependencies:
  nodejs:
    webpack: "*"
    yarn: "*"

# How many resources to devote to the app. Defaults to AUTO in production environments.
relationships:
  clickhouse: "clickhouse:clickhouse"
  postgres: "postgres:postgresql"

# The size of the persistent disk of the application (in MB).
disk: 2048

# Mounts define directories that are writable after the build is complete.
mounts:
   "/storage": # Represents the path in the app.
       source: "local" # "local" sources are unique to the app, while "service" sources can be shared among apps.
       source_path: "storage" # The subdirectory within the mounted disk (the source) where the mount should point.


# Specifies a default set of build tasks to run. Flavors are language-specific.
# More information: https://docs.upsun.com/create-apps/app-reference.html#build
build:
  flavor: none

# Hooks allow you to customize your code/environment as the project moves through the build and deploy stages
hooks:
  # The build hook is run after any build flavor.
  build: |
    set -eux
    export MIX_ENV=prod
    export ENVIRONMENT=prod
    mix local.hex --force
    mix local.rebar --force
    mix deps.get
    mix download_country_database
    npm install --prefix assets
    npm install --prefix tracker
    npm run deploy --prefix ./tracker
    npm run deploy --prefix ./assets
    mix phx.digest priv/static
    mix release plausible
  # The deploy hook is run after the app container has been started, but before it has started accepting requests.
  deploy: |
    set -eux
    # echo 'Put your deploy command here'
    mix ecto.migrate
    

  # The post_deploy hook is run after the app container has been started and after it has started accepting requests.
  # post_deploy: |

# The web key configures the web server running in front of your app.
web:
  # Commands are run once after deployment to start the application process.
  commands:
    # The command to launch your app. If it terminates, it’s restarted immediately.
    # You can use the $PORT or the $SOCKET environment variable depending on the socket family of your upstream
    start: "_build/prod/rel/plausible/bin/plausible start"
  # You can listen to a UNIX socket (unix) or a TCP port (tcp, default).
  # Whether your app should speak to the webserver via TCP or Unix socket. Defaults to tcp
  upstream:
    # Whether your app should speak to the webserver via TCP or Unix socket. Defaults to tcp
    socket_family: tcp
  # Each key in locations is a path on your site with a leading /.
  locations:
    "/":
      passthru: true
      root: "priv/static/"
      request_buffering:
        enabled: false

# Scheduled tasks for the app.
# crons:

